### ISSUE TITLE
Cannot Process $(ProjectDir), $(SolutionDir)

### ISSUE THREAD

**Issue by Aphexus** [TomSmartBishop/image-comments#27]
Says the format of the URI is wrong but. If I put in the absolute path it shows the image. Also, it would be cool if animated gifs or movies could be played too! Maybe require them to be clicked on to play though.

**Comment by TomSmartBishop** [comment]
Can you post an example?

**Comment by TomSmartBishop** [comment]
@Aphexus The latest release shows you the resolved path as tooltip (in case it failed) so you should be able  to figure out what went wrong. For the animation request, please open another issue with a discoverable title so that we can track it separately.
