### ISSUE TITLE
image does not collapse with comment fold/unfold button vs 2017

### ISSUE THREAD

**Issue by ZcuBa** [TomSmartBishop/image-comments#28]
The image is being renderred (and not collapsed) even if the comment it resides in is folded/collapsed.

**Comment by satabol** [comment]
find ImageAdornmentManager.cs
string lineText = line.Extent.GetText();
append
lineText = lineText.Split(new string[] { "\r\n", "\r"}, StringSplitOptions.None)[0];
![fold_unfold comment with image](https://user-images.githubusercontent.com/14288520/53169947-d2b45400-35ef-11e9-9aa9-2d093e2551a8.gif)

**Comment by TomSmartBishop** [comment]
Thanks for the suggestion, already went in.
