### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by SergeyZhurikhin** [TomSmartBishop/image-comments#29]
I have many images in the documentation that have relative paths. This is due to the documentation generator that injects the *resources* folder into the *chm* file and everything grows together; the images appear in the help.
```C#
        /// <remarks>
        /// <para>Text...</para>
        /// <para><image url = "resources\FCAD.bmp" /></para>
        /// <para>Text...</para>
        /// </remarks>
```
 Is it possible to customize the "Default folder = H:\Folder1\Folder2". Thus, a substitution would occur and absolute paths would be computed: H:\Folder1\Folder2\resources\FCAD.bmp, and the image would show.

**Comment by TomSmartBishop** [comment]
Hey @SergeyZhurikhin, the new version now support relative paths (to the source file). Otherwise make your resources relative to the solution or project dir: $(SolutionDir)\test\image.jpg

**Comment by TomSmartBishop** [comment]
I will close this issue for now as we have support for relative paths. Please open a new one if you feel like there is more needed
