### ISSUE TITLE
Support for VS2019 >

### ISSUE THREAD

**Issue by bjthomson** [TomSmartBishop/image-comments#31]
First of all, thanks for a really nice tool. I used it a lot in VS2017, but it doesn't seem to install in 2019.

Is that on the roadmap?

**Comment by robertoandrade** [comment]
wondering what it would take, is it just a matter of changing settings for compatibility or there's actual coding involved?

**Comment by bjthomson** [comment]
I found an alternative on the vs marketplace: "Memeful comments" by Marius Bancila. It does much the same thing, its not quite so slick when scrolling, but does the job.

**Comment by E812** [comment]
I use that one also as an alternative. Good thing is that it uses the same syntax.
Bad thing beside its behavior when scrolling is that it holds an handle to the image file. So when you try to update the image you need to close VS.
I would like to switch back to image-comments if it would support VS2019.

**Comment by lukesdm** [comment]
I've just merged changes from this fork and a VS2019 PR back upstream.
https://github.com/lukesdm/image-comments/pull/29

**Comment by TomSmartBishop** [comment]
@lukesdm and everyone ese, I just merged a PR that also adds VS2019 support. Sorry for the long silence, I didn't pay much attention.

**Comment by TomSmartBishop** [comment]
Now supported
